/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using YNAB.Dotnet.Client;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing BudgetsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class BudgetsApiTests
    {
        private BudgetsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new BudgetsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BudgetsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' BudgetsApi
            //Assert.IsInstanceOfType(typeof(BudgetsApi), instance, "instance is a BudgetsApi");
        }

        
        /// <summary>
        /// Test GetBudgetById
        /// </summary>
        [Test]
        public void GetBudgetByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //int? lastKnowledgeOfServer = null;
            //var response = instance.GetBudgetById(budgetId, lastKnowledgeOfServer);
            //Assert.IsInstanceOf<BudgetDetailResponse> (response, "response is BudgetDetailResponse");
        }
        
        /// <summary>
        /// Test GetBudgetSettingsById
        /// </summary>
        [Test]
        public void GetBudgetSettingsByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //var response = instance.GetBudgetSettingsById(budgetId);
            //Assert.IsInstanceOf<BudgetSettingsResponse> (response, "response is BudgetSettingsResponse");
        }
        
        /// <summary>
        /// Test GetBudgets
        /// </summary>
        [Test]
        public void GetBudgetsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetBudgets();
            //Assert.IsInstanceOf<BudgetSummaryResponse> (response, "response is BudgetSummaryResponse");
        }
        
    }

}
