/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using YNAB.Dotnet.Client;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing CategoriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CategoriesApiTests
    {
        private CategoriesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CategoriesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CategoriesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CategoriesApi
            //Assert.IsInstanceOfType(typeof(CategoriesApi), instance, "instance is a CategoriesApi");
        }

        
        /// <summary>
        /// Test GetCategories
        /// </summary>
        [Test]
        public void GetCategoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //var response = instance.GetCategories(budgetId);
            //Assert.IsInstanceOf<CategoriesResponse> (response, "response is CategoriesResponse");
        }
        
        /// <summary>
        /// Test GetCategoryById
        /// </summary>
        [Test]
        public void GetCategoryByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //Guid? categoryId = null;
            //var response = instance.GetCategoryById(budgetId, categoryId);
            //Assert.IsInstanceOf<CategoryResponse> (response, "response is CategoryResponse");
        }
        
        /// <summary>
        /// Test GetMonthCategoryById
        /// </summary>
        [Test]
        public void GetMonthCategoryByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //DateTime? month = null;
            //Guid? categoryId = null;
            //var response = instance.GetMonthCategoryById(budgetId, month, categoryId);
            //Assert.IsInstanceOf<CategoryResponse> (response, "response is CategoryResponse");
        }
        
        /// <summary>
        /// Test UpdateMonthCategory
        /// </summary>
        [Test]
        public void UpdateMonthCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //DateTime? month = null;
            //Guid? categoryId = null;
            //SaveMonthCategoryWrapper monthCategory = null;
            //var response = instance.UpdateMonthCategory(budgetId, month, categoryId, monthCategory);
            //Assert.IsInstanceOf<CategoryResponse> (response, "response is CategoryResponse");
        }
        
    }

}
