/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using YNAB.Dotnet.Client;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing PayeeLocationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PayeeLocationsApiTests
    {
        private PayeeLocationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PayeeLocationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayeeLocationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PayeeLocationsApi
            //Assert.IsInstanceOfType(typeof(PayeeLocationsApi), instance, "instance is a PayeeLocationsApi");
        }

        
        /// <summary>
        /// Test GetPayeeLocationById
        /// </summary>
        [Test]
        public void GetPayeeLocationByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //Guid? payeeLocationId = null;
            //var response = instance.GetPayeeLocationById(budgetId, payeeLocationId);
            //Assert.IsInstanceOf<PayeeLocationResponse> (response, "response is PayeeLocationResponse");
        }
        
        /// <summary>
        /// Test GetPayeeLocations
        /// </summary>
        [Test]
        public void GetPayeeLocationsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //var response = instance.GetPayeeLocations(budgetId);
            //Assert.IsInstanceOf<PayeeLocationsResponse> (response, "response is PayeeLocationsResponse");
        }
        
        /// <summary>
        /// Test GetPayeeLocationsByPayee
        /// </summary>
        [Test]
        public void GetPayeeLocationsByPayeeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //Guid? payeeId = null;
            //var response = instance.GetPayeeLocationsByPayee(budgetId, payeeId);
            //Assert.IsInstanceOf<PayeeLocationsResponse> (response, "response is PayeeLocationsResponse");
        }
        
    }

}
