/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using YNAB.Dotnet.Client;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing PayeesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PayeesApiTests
    {
        private PayeesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PayeesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PayeesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PayeesApi
            //Assert.IsInstanceOfType(typeof(PayeesApi), instance, "instance is a PayeesApi");
        }

        
        /// <summary>
        /// Test GetPayeeById
        /// </summary>
        [Test]
        public void GetPayeeByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //Guid? payeeId = null;
            //var response = instance.GetPayeeById(budgetId, payeeId);
            //Assert.IsInstanceOf<PayeeResponse> (response, "response is PayeeResponse");
        }
        
        /// <summary>
        /// Test GetPayees
        /// </summary>
        [Test]
        public void GetPayeesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? budgetId = null;
            //var response = instance.GetPayees(budgetId);
            //Assert.IsInstanceOf<PayeesResponse> (response, "response is PayeesResponse");
        }
        
    }

}
