/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;
using YNAB.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing BudgetDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BudgetDetailTests
    {
        // TODO uncomment below to declare an instance variable for BudgetDetail
        //private BudgetDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BudgetDetail
            //instance = new BudgetDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BudgetDetail
        /// </summary>
        [Test]
        public void BudgetDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BudgetDetail
            //Assert.IsInstanceOfType<BudgetDetail> (instance, "variable 'instance' is a BudgetDetail");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LastModifiedOn'
        /// </summary>
        [Test]
        public void LastModifiedOnTest()
        {
            // TODO unit test for the property 'LastModifiedOn'
        }
        /// <summary>
        /// Test the property 'DateFormat'
        /// </summary>
        [Test]
        public void DateFormatTest()
        {
            // TODO unit test for the property 'DateFormat'
        }
        /// <summary>
        /// Test the property 'CurrencyFormat'
        /// </summary>
        [Test]
        public void CurrencyFormatTest()
        {
            // TODO unit test for the property 'CurrencyFormat'
        }
        /// <summary>
        /// Test the property 'Accounts'
        /// </summary>
        [Test]
        public void AccountsTest()
        {
            // TODO unit test for the property 'Accounts'
        }
        /// <summary>
        /// Test the property 'Payees'
        /// </summary>
        [Test]
        public void PayeesTest()
        {
            // TODO unit test for the property 'Payees'
        }
        /// <summary>
        /// Test the property 'PayeeLocations'
        /// </summary>
        [Test]
        public void PayeeLocationsTest()
        {
            // TODO unit test for the property 'PayeeLocations'
        }
        /// <summary>
        /// Test the property 'CategoryGroups'
        /// </summary>
        [Test]
        public void CategoryGroupsTest()
        {
            // TODO unit test for the property 'CategoryGroups'
        }
        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Test]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
        /// <summary>
        /// Test the property 'Months'
        /// </summary>
        [Test]
        public void MonthsTest()
        {
            // TODO unit test for the property 'Months'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'Subtransactions'
        /// </summary>
        [Test]
        public void SubtransactionsTest()
        {
            // TODO unit test for the property 'Subtransactions'
        }
        /// <summary>
        /// Test the property 'ScheduledTransactions'
        /// </summary>
        [Test]
        public void ScheduledTransactionsTest()
        {
            // TODO unit test for the property 'ScheduledTransactions'
        }
        /// <summary>
        /// Test the property 'ScheduledSubtransactions'
        /// </summary>
        [Test]
        public void ScheduledSubtransactionsTest()
        {
            // TODO unit test for the property 'ScheduledSubtransactions'
        }

    }

}
