/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;
using YNAB.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing BudgetSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BudgetSummaryTests
    {
        // TODO uncomment below to declare an instance variable for BudgetSummary
        //private BudgetSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BudgetSummary
            //instance = new BudgetSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BudgetSummary
        /// </summary>
        [Test]
        public void BudgetSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BudgetSummary
            //Assert.IsInstanceOfType<BudgetSummary> (instance, "variable 'instance' is a BudgetSummary");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LastModifiedOn'
        /// </summary>
        [Test]
        public void LastModifiedOnTest()
        {
            // TODO unit test for the property 'LastModifiedOn'
        }
        /// <summary>
        /// Test the property 'DateFormat'
        /// </summary>
        [Test]
        public void DateFormatTest()
        {
            // TODO unit test for the property 'DateFormat'
        }
        /// <summary>
        /// Test the property 'CurrencyFormat'
        /// </summary>
        [Test]
        public void CurrencyFormatTest()
        {
            // TODO unit test for the property 'CurrencyFormat'
        }

    }

}
