/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;
using YNAB.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing Category
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CategoryTests
    {
        // TODO uncomment below to declare an instance variable for Category
        //private Category instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Category
            //instance = new Category();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Category
        /// </summary>
        [Test]
        public void CategoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Category
            //Assert.IsInstanceOfType<Category> (instance, "variable 'instance' is a Category");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CategoryGroupId'
        /// </summary>
        [Test]
        public void CategoryGroupIdTest()
        {
            // TODO unit test for the property 'CategoryGroupId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Test]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }
        /// <summary>
        /// Test the property 'OriginalCategoryGroupId'
        /// </summary>
        [Test]
        public void OriginalCategoryGroupIdTest()
        {
            // TODO unit test for the property 'OriginalCategoryGroupId'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Budgeted'
        /// </summary>
        [Test]
        public void BudgetedTest()
        {
            // TODO unit test for the property 'Budgeted'
        }
        /// <summary>
        /// Test the property 'Activity'
        /// </summary>
        [Test]
        public void ActivityTest()
        {
            // TODO unit test for the property 'Activity'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'GoalType'
        /// </summary>
        [Test]
        public void GoalTypeTest()
        {
            // TODO unit test for the property 'GoalType'
        }
        /// <summary>
        /// Test the property 'GoalCreationMonth'
        /// </summary>
        [Test]
        public void GoalCreationMonthTest()
        {
            // TODO unit test for the property 'GoalCreationMonth'
        }
        /// <summary>
        /// Test the property 'GoalTarget'
        /// </summary>
        [Test]
        public void GoalTargetTest()
        {
            // TODO unit test for the property 'GoalTarget'
        }
        /// <summary>
        /// Test the property 'GoalTargetMonth'
        /// </summary>
        [Test]
        public void GoalTargetMonthTest()
        {
            // TODO unit test for the property 'GoalTargetMonth'
        }
        /// <summary>
        /// Test the property 'GoalPercentageComplete'
        /// </summary>
        [Test]
        public void GoalPercentageCompleteTest()
        {
            // TODO unit test for the property 'GoalPercentageComplete'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Test]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

    }

}
