/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;
using YNAB.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing CurrencyFormat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CurrencyFormatTests
    {
        // TODO uncomment below to declare an instance variable for CurrencyFormat
        //private CurrencyFormat instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CurrencyFormat
            //instance = new CurrencyFormat();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CurrencyFormat
        /// </summary>
        [Test]
        public void CurrencyFormatInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CurrencyFormat
            //Assert.IsInstanceOfType<CurrencyFormat> (instance, "variable 'instance' is a CurrencyFormat");
        }


        /// <summary>
        /// Test the property 'IsoCode'
        /// </summary>
        [Test]
        public void IsoCodeTest()
        {
            // TODO unit test for the property 'IsoCode'
        }
        /// <summary>
        /// Test the property 'ExampleFormat'
        /// </summary>
        [Test]
        public void ExampleFormatTest()
        {
            // TODO unit test for the property 'ExampleFormat'
        }
        /// <summary>
        /// Test the property 'DecimalDigits'
        /// </summary>
        [Test]
        public void DecimalDigitsTest()
        {
            // TODO unit test for the property 'DecimalDigits'
        }
        /// <summary>
        /// Test the property 'DecimalSeparator'
        /// </summary>
        [Test]
        public void DecimalSeparatorTest()
        {
            // TODO unit test for the property 'DecimalSeparator'
        }
        /// <summary>
        /// Test the property 'SymbolFirst'
        /// </summary>
        [Test]
        public void SymbolFirstTest()
        {
            // TODO unit test for the property 'SymbolFirst'
        }
        /// <summary>
        /// Test the property 'GroupSeparator'
        /// </summary>
        [Test]
        public void GroupSeparatorTest()
        {
            // TODO unit test for the property 'GroupSeparator'
        }
        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Test]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }
        /// <summary>
        /// Test the property 'DisplaySymbol'
        /// </summary>
        [Test]
        public void DisplaySymbolTest()
        {
            // TODO unit test for the property 'DisplaySymbol'
        }

    }

}
