/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;
using YNAB.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing SaveTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SaveTransactionTests
    {
        // TODO uncomment below to declare an instance variable for SaveTransaction
        //private SaveTransaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SaveTransaction
            //instance = new SaveTransaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SaveTransaction
        /// </summary>
        [Test]
        public void SaveTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SaveTransaction
            //Assert.IsInstanceOfType<SaveTransaction> (instance, "variable 'instance' is a SaveTransaction");
        }


        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'PayeeId'
        /// </summary>
        [Test]
        public void PayeeIdTest()
        {
            // TODO unit test for the property 'PayeeId'
        }
        /// <summary>
        /// Test the property 'PayeeName'
        /// </summary>
        [Test]
        public void PayeeNameTest()
        {
            // TODO unit test for the property 'PayeeName'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Test]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'Cleared'
        /// </summary>
        [Test]
        public void ClearedTest()
        {
            // TODO unit test for the property 'Cleared'
        }
        /// <summary>
        /// Test the property 'Approved'
        /// </summary>
        [Test]
        public void ApprovedTest()
        {
            // TODO unit test for the property 'Approved'
        }
        /// <summary>
        /// Test the property 'FlagColor'
        /// </summary>
        [Test]
        public void FlagColorTest()
        {
            // TODO unit test for the property 'FlagColor'
        }
        /// <summary>
        /// Test the property 'ImportId'
        /// </summary>
        [Test]
        public void ImportIdTest()
        {
            // TODO unit test for the property 'ImportId'
        }

    }

}
