/* 
 * YNAB API Endpoints
 *
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YNAB.Dotnet.Api;
using YNAB.Dotnet.Model;
using YNAB.Dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YNAB.Dotnet.Tests
{
    /// <summary>
    ///  Class for testing ScheduledTransactionSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduledTransactionSummaryTests
    {
        // TODO uncomment below to declare an instance variable for ScheduledTransactionSummary
        //private ScheduledTransactionSummary instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduledTransactionSummary
            //instance = new ScheduledTransactionSummary();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduledTransactionSummary
        /// </summary>
        [Test]
        public void ScheduledTransactionSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScheduledTransactionSummary
            //Assert.IsInstanceOfType<ScheduledTransactionSummary> (instance, "variable 'instance' is a ScheduledTransactionSummary");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DateFirst'
        /// </summary>
        [Test]
        public void DateFirstTest()
        {
            // TODO unit test for the property 'DateFirst'
        }
        /// <summary>
        /// Test the property 'DateNext'
        /// </summary>
        [Test]
        public void DateNextTest()
        {
            // TODO unit test for the property 'DateNext'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Test]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Test]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'FlagColor'
        /// </summary>
        [Test]
        public void FlagColorTest()
        {
            // TODO unit test for the property 'FlagColor'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'PayeeId'
        /// </summary>
        [Test]
        public void PayeeIdTest()
        {
            // TODO unit test for the property 'PayeeId'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'TransferAccountId'
        /// </summary>
        [Test]
        public void TransferAccountIdTest()
        {
            // TODO unit test for the property 'TransferAccountId'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Test]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

    }

}
